// <auto-generated />
using System;
using IncidentManagement.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentManagement.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818165334_AddWorkflowIncidentAssignments")]
    partial class AddWorkflowIncidentAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("IncidentManagement.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Login failures, password resets, portal access issues",
                            Name = "Login/Portal Access"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Payment processing, disbursement delays or failures",
                            Name = "Payment/Disbursement"
                        },
                        new
                        {
                            Id = 3,
                            Description = "KYC document verification issues",
                            Name = "KYC/Verification"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bank account, IFSC, penny drop verification",
                            Name = "Bank Details/IFSC/Penny Drop"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Lead or application status queries",
                            Name = "Lead/Application Status"
                        },
                        new
                        {
                            Id = 6,
                            Description = "App crashes, bugs, technical errors",
                            Name = "App/Technical Error"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Phone/connectivity issues",
                            Name = "Call/Connectivity"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Document upload failures or issues",
                            Name = "Document/Upload"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Any other general query",
                            Name = "Other/General Query"
                        });
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaggedUserIds")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("IncidentId", "CreatedAt");

                    b.ToTable("Comments", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentAssigneeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RejectedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RevertCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TicketRef")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CurrentAssigneeId");

                    b.HasIndex("RejectedById");

                    b.HasIndex("ReporterId");

                    b.HasIndex("Status");

                    b.HasIndex("TicketRef")
                        .IsUnique();

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.IncidentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignmentType")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ResolverId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResolverId");

                    b.HasIndex("IncidentId", "AssignedAt");

                    b.ToTable("IncidentAssignments", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId", "ReadAt");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Mobile")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CreatedById");

                    b.ToTable("Workflows", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowCategory", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("WorkflowId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("WorkflowCategories", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowIncidentAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AttachedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AttachedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("VisibleInComments")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AttachedById");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("IncidentId", "WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowIncidentAssignments", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Required")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "FieldName")
                        .IsUnique();

                    b.ToTable("WorkflowInputs", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FailedStepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TriggeredById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("TriggeredById");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowRuns", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowRunCounter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IncidentId");

                    b.HasIndex("UserId", "IncidentId")
                        .IsUnique();

                    b.ToTable("WorkflowRunCounters", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthConfigEncrypted")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<int>("AuthType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BodyTemplate")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UrlTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "StepOrder")
                        .IsUnique();

                    b.ToTable("WorkflowSteps", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasMaxLength(100000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StepId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RunId", "StepOrder");

                    b.ToTable("WorkflowStepResults", (string)null);
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Comment", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.Incident", "Incident")
                        .WithMany("Comments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Incident", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.User", "CurrentAssignee")
                        .WithMany("AssignedIncidents")
                        .HasForeignKey("CurrentAssigneeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentManagement.Api.Domain.User", "RejectedBy")
                        .WithMany()
                        .HasForeignKey("RejectedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IncidentManagement.Api.Domain.User", "Reporter")
                        .WithMany("ReportedIncidents")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CurrentAssignee");

                    b.Navigation("RejectedBy");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.IncidentAssignment", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Incident", "Incident")
                        .WithMany("Assignments")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Notification", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentManagement.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Workflow", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowCategory", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Category", "Category")
                        .WithMany("Workflows")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.Workflow", "Workflow")
                        .WithMany("Categories")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowIncidentAssignment", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.User", "AttachedBy")
                        .WithMany()
                        .HasForeignKey("AttachedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttachedBy");

                    b.Navigation("Incident");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowInput", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Workflow", "Workflow")
                        .WithMany("Inputs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowRun", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IncidentManagement.Api.Domain.User", "TriggeredBy")
                        .WithMany()
                        .HasForeignKey("TriggeredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.Workflow", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("TriggeredBy");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowRunCounter", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IncidentManagement.Api.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incident");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowStep", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.Workflow", "Workflow")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowStepResult", b =>
                {
                    b.HasOne("IncidentManagement.Api.Domain.WorkflowRun", "Run")
                        .WithMany("StepResults")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Category", b =>
                {
                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Incident", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.User", b =>
                {
                    b.Navigation("AssignedIncidents");

                    b.Navigation("ReportedIncidents");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.Workflow", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Inputs");

                    b.Navigation("Runs");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("IncidentManagement.Api.Domain.WorkflowRun", b =>
                {
                    b.Navigation("StepResults");
                });
#pragma warning restore 612, 618
        }
    }
}
